# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ProjectInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'instructions': 'str',
        'locale': 'str',
        'name': 'str',
        'per_task_instructions': 'str',
        'short_description': 'str'
    }

    attribute_map = {
        'description': 'description',
        'instructions': 'instructions',
        'locale': 'locale',
        'name': 'name',
        'per_task_instructions': 'perTaskInstructions',
        'short_description': 'shortDescription'
    }

    def __init__(self, description='Awesome little project and a little bit more', instructions='Complete the tasks', locale='en', name='Thinkwhere Project', per_task_instructions='Use Thinkwhere Imagery Only', short_description='Awesome little project'):  # noqa: E501
        """ProjectInfo - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._instructions = None
        self._locale = None
        self._name = None
        self._per_task_instructions = None
        self._short_description = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if instructions is not None:
            self.instructions = instructions
        if locale is not None:
            self.locale = locale
        if name is not None:
            self.name = name
        if per_task_instructions is not None:
            self.per_task_instructions = per_task_instructions
        if short_description is not None:
            self.short_description = short_description

    @property
    def description(self):
        """Gets the description of this ProjectInfo.  # noqa: E501


        :return: The description of this ProjectInfo.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ProjectInfo.


        :param description: The description of this ProjectInfo.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def instructions(self):
        """Gets the instructions of this ProjectInfo.  # noqa: E501


        :return: The instructions of this ProjectInfo.  # noqa: E501
        :rtype: str
        """
        return self._instructions

    @instructions.setter
    def instructions(self, instructions):
        """Sets the instructions of this ProjectInfo.


        :param instructions: The instructions of this ProjectInfo.  # noqa: E501
        :type: str
        """

        self._instructions = instructions

    @property
    def locale(self):
        """Gets the locale of this ProjectInfo.  # noqa: E501


        :return: The locale of this ProjectInfo.  # noqa: E501
        :rtype: str
        """
        return self._locale

    @locale.setter
    def locale(self, locale):
        """Sets the locale of this ProjectInfo.


        :param locale: The locale of this ProjectInfo.  # noqa: E501
        :type: str
        """

        self._locale = locale

    @property
    def name(self):
        """Gets the name of this ProjectInfo.  # noqa: E501


        :return: The name of this ProjectInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProjectInfo.


        :param name: The name of this ProjectInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def per_task_instructions(self):
        """Gets the per_task_instructions of this ProjectInfo.  # noqa: E501


        :return: The per_task_instructions of this ProjectInfo.  # noqa: E501
        :rtype: str
        """
        return self._per_task_instructions

    @per_task_instructions.setter
    def per_task_instructions(self, per_task_instructions):
        """Sets the per_task_instructions of this ProjectInfo.


        :param per_task_instructions: The per_task_instructions of this ProjectInfo.  # noqa: E501
        :type: str
        """

        self._per_task_instructions = per_task_instructions

    @property
    def short_description(self):
        """Gets the short_description of this ProjectInfo.  # noqa: E501


        :return: The short_description of this ProjectInfo.  # noqa: E501
        :rtype: str
        """
        return self._short_description

    @short_description.setter
    def short_description(self, short_description):
        """Sets the short_description of this ProjectInfo.


        :param short_description: The short_description of this ProjectInfo.  # noqa: E501
        :type: str
        """

        self._short_description = short_description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
