# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class TaskUpdateUnlock(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'comment': 'str',
        'status': 'str'
    }

    attribute_map = {
        'comment': 'comment',
        'status': 'status'
    }

    def __init__(self, comment='Comment about the mapping', status='MAPPED'):  # noqa: E501
        """TaskUpdateUnlock - a model defined in Swagger"""  # noqa: E501
        self._comment = None
        self._status = None
        self.discriminator = None
        if comment is not None:
            self.comment = comment
        self.status = status

    @property
    def comment(self):
        """Gets the comment of this TaskUpdateUnlock.  # noqa: E501

        Optional user comment about the task  # noqa: E501

        :return: The comment of this TaskUpdateUnlock.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this TaskUpdateUnlock.

        Optional user comment about the task  # noqa: E501

        :param comment: The comment of this TaskUpdateUnlock.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def status(self):
        """Gets the status of this TaskUpdateUnlock.  # noqa: E501

        The new status for the task  # noqa: E501

        :return: The status of this TaskUpdateUnlock.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TaskUpdateUnlock.

        The new status for the task  # noqa: E501

        :param status: The status of this TaskUpdateUnlock.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskUpdateUnlock, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskUpdateUnlock):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
