# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.project_admin_api import ProjectAdminApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectAdminApi(unittest.TestCase):
    """ProjectAdminApi unit test stubs"""

    def setUp(self):
        self.api = api.project_admin_api.ProjectAdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_admin_my_projects_get(self):
        """Test case for api_v1_admin_my_projects_get

        Get all projects for logged in admin  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_comments_get(self):
        """Test case for api_v1_admin_project_project_id_comments_get

        Gets all comments for project  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_delete(self):
        """Test case for api_v1_admin_project_project_id_delete

        Deletes a Tasking-Manager project  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_get(self):
        """Test case for api_v1_admin_project_project_id_get

        Retrieves a Tasking-Manager project  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_invalidate_all_post(self):
        """Test case for api_v1_admin_project_project_id_invalidate_all_post

        Invalidate all mapped tasks on a project  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_map_all_post(self):
        """Test case for api_v1_admin_project_project_id_map_all_post

        Map all tasks on a project  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_post(self):
        """Test case for api_v1_admin_project_project_id_post

        Updates a Tasking-Manager project  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_reset_all_badimagery_post(self):
        """Test case for api_v1_admin_project_project_id_reset_all_badimagery_post

        Mark all bad imagery tasks ready for mapping  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_reset_all_post(self):
        """Test case for api_v1_admin_project_project_id_reset_all_post

        Reset all tasks on project back to ready, preserving history.  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_transfer_post(self):
        """Test case for api_v1_admin_project_project_id_transfer_post

        Transfers a project to a new user.  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_project_id_validate_all_post(self):
        """Test case for api_v1_admin_project_project_id_validate_all_post

        Validate all mapped tasks on a project  # noqa: E501
        """
        pass

    def test_api_v1_admin_project_put(self):
        """Test case for api_v1_admin_project_put

        Creates a tasking-manager project  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_annotations_annotation_type_get(self):
        """Test case for api_v1_project_project_id_task_annotations_annotation_type_get

        Get all task annotations for a project  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_annotations_annotation_type_post(self):
        """Test case for api_v1_project_project_id_task_annotations_annotation_type_post

        Store new task annotations for tasks of a project  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_annotations_get(self):
        """Test case for api_v1_project_project_id_task_annotations_get

        Get all task annotations for a project  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_annotations_post(self):
        """Test case for api_v1_project_project_id_task_annotations_post

        Store new task annotations for tasks of a project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
