# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.docs_api import DocsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDocsApi(unittest.TestCase):
    """DocsApi unit test stubs"""

    def setUp(self):
        self.api = api.docs_api.DocsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_docs_get(self):
        """Test case for api_docs_get

        Generates Swagger UI readable JSON  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
