# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.licenses_api import LicensesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLicensesApi(unittest.TestCase):
    """LicensesApi unit test stubs"""

    def setUp(self):
        self.api = api.licenses_api.LicensesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_license_license_id_delete(self):
        """Test case for api_v1_license_license_id_delete

        Delete the specified mapping license  # noqa: E501
        """
        pass

    def test_api_v1_license_license_id_get(self):
        """Test case for api_v1_license_license_id_get

        Get specified mapping license  # noqa: E501
        """
        pass

    def test_api_v1_license_license_id_post(self):
        """Test case for api_v1_license_license_id_post

        Update  a new mapping license  # noqa: E501
        """
        pass

    def test_api_v1_license_list_get(self):
        """Test case for api_v1_license_list_get

        Get all imagery licenses  # noqa: E501
        """
        pass

    def test_api_v1_license_put(self):
        """Test case for api_v1_license_put

        Creates a new mapping license  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
