# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.settings_api import SettingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSettingsApi(unittest.TestCase):
    """SettingsApi unit test stubs"""

    def setUp(self):
        self.api = api.settings_api.SettingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_settings_get(self):
        """Test case for api_v1_settings_get

        Gets all supported languages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
