# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.grid_api import GridApi  # noqa: E501
from swagger_client.rest import ApiException


class TestGridApi(unittest.TestCase):
    """GridApi unit test stubs"""

    def setUp(self):
        self.api = api.grid_api.GridApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_grid_intersecting_tiles_put(self):
        """Test case for api_v1_grid_intersecting_tiles_put

        Gets the tiles intersecting the aoi  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_task_id_split_post(self):
        """Test case for api_v1_project_project_id_task_task_id_split_post

        Split a task  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
