# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.mapping_api import MappingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMappingApi(unittest.TestCase):
    """MappingApi unit test stubs"""

    def setUp(self):
        self.api = api.mapping_api.MappingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_project_project_id_aoi_get(self):
        """Test case for api_v1_project_project_id_aoi_get

        Get AOI of Project  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_get(self):
        """Test case for api_v1_project_project_id_get

        Get HOT Project for mapping  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_has_user_locked_tasks_details_get(self):
        """Test case for api_v1_project_project_id_has_user_locked_tasks_details_get

        Gets details of any locked task on the project from logged in user  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_has_user_locked_tasks_get(self):
        """Test case for api_v1_project_project_id_has_user_locked_tasks_get

        Gets any locked task on the project from logged in user  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_summary_get(self):
        """Test case for api_v1_project_project_id_summary_get

        Gets project summary  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_task_id_comment_post(self):
        """Test case for api_v1_project_project_id_task_task_id_comment_post

        Adds a comment to the task outside of mapping/validation  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_task_id_get(self):
        """Test case for api_v1_project_project_id_task_task_id_get

        Get task for mapping  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_task_id_lock_for_mapping_post(self):
        """Test case for api_v1_project_project_id_task_task_id_lock_for_mapping_post

        Locks the task for mapping  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_task_id_stop_mapping_post(self):
        """Test case for api_v1_project_project_id_task_task_id_stop_mapping_post

        Unlock task that is locked for mapping resetting it to it's last status  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_task_id_undo_mapping_post(self):
        """Test case for api_v1_project_project_id_task_task_id_undo_mapping_post

        Get task for mapping  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_task_task_id_unlock_after_mapping_post(self):
        """Test case for api_v1_project_project_id_task_task_id_unlock_after_mapping_post

        Unlocks the task after mapping completed  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_tasks_as_gpx_get(self):
        """Test case for api_v1_project_project_id_tasks_as_gpx_get

        Get tasks as GPX  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_tasks_as_osm_xml_get(self):
        """Test case for api_v1_project_project_id_tasks_as_osm_xml_get

        Get tasks as OSM XML  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_tasks_get(self):
        """Test case for api_v1_project_project_id_tasks_get

        Get tasks as JSON  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
