# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.reset_task import ResetTask  # noqa: E501
from swagger_client.rest import ApiException


class TestResetTask(unittest.TestCase):
    """ResetTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResetTask(self):
        """Test ResetTask"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.reset_task.ResetTask()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
