# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.geo_json_feature import GeoJsonFeature  # noqa: E501
from swagger_client.rest import ApiException


class TestGeoJsonFeature(unittest.TestCase):
    """GeoJsonFeature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoJsonFeature(self):
        """Test GeoJsonFeature"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.geo_json_feature.GeoJsonFeature()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
