# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.authentication_api import AuthenticationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = api.authentication_api.AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_auth_email_get(self):
        """Test case for api_auth_email_get

        Authenticates user owns email address  # noqa: E501
        """
        pass

    def test_api_v1_auth_login_get(self):
        """Test case for api_v1_auth_login_get

        Redirects user to OSM to authenticate  # noqa: E501
        """
        pass

    def test_api_v1_auth_oauth_callback_get(self):
        """Test case for api_v1_auth_oauth_callback_get

        Handles the OSM OAuth callback  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
