# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.mapping_issues_api import MappingIssuesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMappingIssuesApi(unittest.TestCase):
    """MappingIssuesApi unit test stubs"""

    def setUp(self):
        self.api = api.mapping_issues_api.MappingIssuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_mapping_issue_categories_get(self):
        """Test case for api_v1_mapping_issue_categories_get

        Gets all mapping issue categories  # noqa: E501
        """
        pass

    def test_api_v1_mapping_issue_category_category_id_delete(self):
        """Test case for api_v1_mapping_issue_category_category_id_delete

        Delete the specified mapping-issue category. Note that categories can  # noqa: E501
        """
        pass

    def test_api_v1_mapping_issue_category_category_id_get(self):
        """Test case for api_v1_mapping_issue_category_category_id_get

        Get specified mapping-issue category  # noqa: E501
        """
        pass

    def test_api_v1_mapping_issue_category_category_id_put(self):
        """Test case for api_v1_mapping_issue_category_category_id_put

        Update an existing mapping-issue category  # noqa: E501
        """
        pass

    def test_api_v1_mapping_issue_category_post(self):
        """Test case for api_v1_mapping_issue_category_post

        Creates a new mapping-issue category  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
