# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.task_comment import TaskComment  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskComment(unittest.TestCase):
    """TaskComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskComment(self):
        """Test TaskComment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.task_comment.TaskComment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
