# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.validation_api import ValidationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestValidationApi(unittest.TestCase):
    """ValidationApi unit test stubs"""

    def setUp(self):
        self.api = api.validation_api.ValidationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_project_project_id_lock_for_validation_post(self):
        """Test case for api_v1_project_project_id_lock_for_validation_post

        Lock tasks for validation  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_mapped_tasks_by_user_get(self):
        """Test case for api_v1_project_project_id_mapped_tasks_by_user_get

        Get mapped tasks grouped by user  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_stop_validating_post(self):
        """Test case for api_v1_project_project_id_stop_validating_post

        Unlock tasks that are locked for validation resetting them to their last status  # noqa: E501
        """
        pass

    def test_api_v1_project_project_id_unlock_after_validation_post(self):
        """Test case for api_v1_project_project_id_unlock_after_validation_post

        Unlocks tasks after validation completed  # noqa: E501
        """
        pass

    def test_api_v1_user_username_invalidated_tasks_get(self):
        """Test case for api_v1_user_username_invalidated_tasks_get

        Get invalidated tasks either mapped by user or invalidated by user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
