# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.health_check_api import HealthCheckApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHealthCheckApi(unittest.TestCase):
    """HealthCheckApi unit test stubs"""

    def setUp(self):
        self.api = api.health_check_api.HealthCheckApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_health_check_get(self):
        """Test case for api_health_check_get

        Simple health-check, if this is unreachable load balancers should be configures to raise an alert  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
