# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.application_api import ApplicationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicationApi(unittest.TestCase):
    """ApplicationApi unit test stubs"""

    def setUp(self):
        self.api = api.application_api.ApplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_application_application_key_delete(self):
        """Test case for api_v1_application_application_key_delete

        Deletes an application key for a user  # noqa: E501
        """
        pass

    def test_api_v1_application_application_key_put(self):
        """Test case for api_v1_application_application_key_put

        Checks the validity of an application key  # noqa: E501
        """
        pass

    def test_api_v1_application_get(self):
        """Test case for api_v1_application_get

        Gets application keys for a user  # noqa: E501
        """
        pass

    def test_api_v1_application_post(self):
        """Test case for api_v1_application_post

        Creates an application key for the user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
