# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.search_api import SearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_project_search_get(self):
        """Test case for api_v1_project_search_get

        Search active projects  # noqa: E501
        """
        pass

    def test_api_v1_projects_within_bounding_box_get(self):
        """Test case for api_v1_projects_within_bounding_box_get

        Search for projects by bbox projects  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
