# coding: utf-8

"""
    HOT Tasking Manager API

    API endpoints for the HOT tasking manager  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.tags_api import TagsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = api.tags_api.TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_v1_tags_campaigns_get(self):
        """Test case for api_v1_tags_campaigns_get

        Gets all campaign tags  # noqa: E501
        """
        pass

    def test_api_v1_tags_organisations_get(self):
        """Test case for api_v1_tags_organisations_get

        Gets all organisation tags  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
